REQUIRE_EVERYONE:int = 0
REQUIRE_BOOST:int = 1
REQUIRE_REGULAR:int = 2
REQUIRE_MOD:int = 3
REQUIRE_OWNER:int = 4
REQUIRE_SYSTEM:int = 5

LEVEL_COOLDOWN:int = 3

COMMAND_COOLDOWN_MIN:int = 3
COMMAND_COOLDOWN_MAX:int = 600

PUNISH_TIME_MIN:int = 3
PUNISH_TIME_MAX:int = 600

QUOTE_AMOUNT:int = 100
COMMAND_AMOUNT:int = 100
ASSIGNROLE_AMOUNT:int = 25
LEVEL_MEDAL_AMOUNT:int = 25
REGULAR_AMOUNT:int = 25
