REQUIRE_EVERYONE:int = 0
REQUIRE_SUB:int = 1
REQUIRE_VIP:int = 2
REQUIRE_REGULAR:int = 3
REQUIRE_MOD:int = 4
REQUIRE_OWNER:int = 5
REQUIRE_ADMIN:int = 6
REQUIRE_SYSTEM:int = 7

LEVEL_COOLDOWN:int = 3

COMMAND_COOLDOWN_MIN:int = 3
COMMAND_COOLDOWN_MAX:int = 600

PUNISH_TIME_MIN:int = 3
PUNISH_TIME_MAX:int = 600

QUOTE_AMOUNT:int = 100
COMMAND_AMOUNT:int = 100
